version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db_container
    env_file: database.conf
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql

volumes:
  db: