version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db_container
    env_file: database.conf
    volumes: 
      - db:/var/lib/postgresql
    networks:
      - db
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5000:5000"
    env_file: database.conf
    restart: unless-stopped
    depends_on: 
      - postgres_db
    networks: 
      - db
    volumes:
      - app:/data

volumes:
  db:
  app:

networks:
  db: